// Generated by https://quicktype.io

export interface ModelPatients {
    patientId: string;
    firstName: string;
    lastName: string;
    gender: string;
    dateOfBirth: string;
    addressLine1: string;
    addressLine2: null | string;
    city: string;
    state: string;
    postalCode: string;
}
